import { LevelConfig } from './index';

export const lesson1Level: LevelConfig = {
  name: "Lesson 1",
  subtitle: "Lumi Commands",
  instructions: "Guide Lumi to the flag! Help Lumi navigate straight up and turn right to reach the flag.",
  gridCols: 3,
  gridRows: 3,
  startPos: { r: 2, c: 0 },
  startDir: 'up',
  flagPos: { r: 0, c: 2 },
  obstacles: [
    { r: 1, c: 1, type: 'rock' },
    { r: 2, c: 1, type: 'tree' },
  ],
  maxSlots: 5,
  hints: ["straight", "straight", "right", "straight", "straight"],

  dimensions: {
    platformWidth: '320px',
    platformHeight: '270px',
    playerWidth: '18%',
    flagWidth: '17%',
    obstacleWidth: '13%',
    playerTransform: 'translate(-57%, -98%)',
    flagTransform: 'translate(-35%, -95%)',
    obstacleRockTransform: 'translate(-50%, -50%)',
    obstacleTreeTransform: 'translate(-50%, -50%)',
    tileHighlightScaleY: '1',
    tileHighlightRadius: '13px',
  },

  tileCoordinates: {
    // ━━━ Row 0 (Top Row) - Smallest tiles (perspective) ━━━
    '0,0': {
      x: 21.5,
      y: 22,
      width: '30%',
      height: '22%',
      playerOffset: { x: 0, y: 0 },
      flagOffset: { x: 0, y: 0 },
      obstacleOffset: { x: 0, y: 0 },
      highlightOffset: { x: 0, y: 0 },
    },
    '0,1': {
      x: 50,
      y: 22,
      width: '31%',
      height: '22%',
      playerOffset: { x: 0, y: 0 },
      flagOffset: { x: 0, y: 0 },
      obstacleOffset: { x: 0, y: 0 },
      highlightOffset: { x: 0, y: 0 },
    },
    '0,2': {
      x: 79,
      y: 22,
      width: '30%',
      height: '22%',
      playerOffset: { x: 0, y: 0 },
      flagOffset: { x: 0, y: 0 },
      obstacleOffset: { x: 0, y: 0 },
      highlightOffset: { x: 0, y: 0 },
    },

    // ━━━ Row 1 (Middle Row) - Medium tiles ━━━
    '1,0': {
      x: 20,
      y: 45,
      width: '31%',
      height: '24%',
      playerOffset: { x: 0, y: 0 },
      flagOffset: { x: 0, y: 0 },
      obstacleOffset: { x: 0, y: 0 },
      highlightOffset: { x: 0, y: 0 },
    },
    '1,1': {
      x: 50,
      y: 43,
      width: '33%',
      height: '22%',
      playerOffset: { x: 0, y: 0 },
      flagOffset: { x: 0, y: 0 },
      obstacleOffset: { x: 0, y: 0 },
      highlightOffset: { x: 0, y: 0 },
    },
    '1,2': {
      x: 84,
      y: 41,
      width: '32%',
      height: '22%',
      playerOffset: { x: 0, y: 0 },
      flagOffset: { x: 0, y: 0 },
      obstacleOffset: { x: 0, y: 0 },
      highlightOffset: { x: 0, y: 0 },
    },

    // ━━━ Row 2 (Bottom Row) - Largest tiles (closest) ━━━
    '2,0': {
      x: 18,
      y: 68,
      width: '32%',
      height: '25%',
      playerOffset: { x: 0, y: 0 },
      flagOffset: { x: 0, y: 0 },
      obstacleOffset: { x: 0, y: 0 },
      highlightOffset: { x: 0, y: 0 },
    },
    '2,1': {
      x: 50,
      y: 66,
      width: '34%',
      height: '25%',
      playerOffset: { x: 0, y: 0 },
      flagOffset: { x: 0, y: 0 },
      obstacleOffset: { x: 0, y: 0 },
      highlightOffset: { x: 0, y: 0 },
    },
    '2,2': {
      x: 84,
      y: 64,
      width: '33%',
      height: '25%',
      playerOffset: { x: 0, y: 0 },
      flagOffset: { x: 0, y: 0 },
      obstacleOffset: { x: 0, y: 0 },
      highlightOffset: { x: 0, y: 0 },
    },
  },
};